name: Releases

on:
  pull_request:
  push:
    branches:
      - master
  release:
    types:
      - created

jobs:
  publish:
    name: Publish assets
    runs-on: "ubuntu-latest"
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: QuTech-Delft/GitHub-Actions/actions/python/poetry-release@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
