name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  testing:
    uses: qutech-delft/github-actions/.github/workflows/poetry-tests.yaml@master
    with:
      e2e_path: 'tests/e2e_test.py'
      idp_url: 'https://quantum-inspire-staging.eu.auth0.com'
      default_host: 'https://staging.qi2.quantum-inspire.com'
      api_audience: 'compute-job-manager'
    secrets:
      e2e_username:  ${{ secrets.E2E_USERNAME }}
      e2e_password:  ${{ secrets.E2E_PASSWORD }}
      idp_client_id: ${{ secrets.IDP_CLIENT_ID }}
