name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  testing:
    uses: qutech-delft/github-actions/.github/workflows/poetry-tests.yaml@master
    secrets:
      e2e_username:  ${{ secrets.E2E_USERNAME }}
      e2e_password:  ${{ secrets.E2E_PASSWORD }}
